### PR TITLE
Complete crud for songs

### PR DESCRIPTION
**Pull request by JoeMcDonough15**

### CODE REVIEW

**Comment by JoeMcDonough15** [comment]
turned off pre-commit and pre-push hooks because of an issue where I'm calling a useAppSelector after a possible return; react doesn't like this and it's marked as a problem by eslint.  Working as expected when I run the app, but I think this is why github actions are not passing.

**Comment by ultrabear** [comment]
> turned off pre-commit and pre-push hooks because of an issue where I'm calling a useAppSelector after a possible return; react doesn't like this and it's marked as a problem by eslint. Working as expected when I run the app, but I think this is why github actions are not passing.

This is something we have to fix, react hooks being called non deterministically causes components to become buggy, it breaks the entire react model, you can expect things like components to not rerender as expected on a change (leading to a broken UX), or rerender unnecessarily multiple times dragging down performance

**Comment by ultrabear** [comment]
Also it looks like CI is failing because of formatting

**Comment by ultrabear** [comment]
> > turned off pre-commit and pre-push hooks because of an issue where I'm calling a useAppSelector after a possible return; react doesn't like this and it's marked as a problem by eslint. Working as expected when I run the app, but I think this is why github actions are not passing.
> 
> This is something we have to fix, react hooks being called non deterministically causes components to become buggy, it breaks the entire react model, you can expect things like components to not rerender as expected on a change (leading to a broken UX), or rerender unnecessarily multiple times dragging down performance

And, unfortunately, the easiest fix for this is to just call all of the hooks unconditionally, and do logical checks to see if we actually want to use or discard that data afterwards
The better fix is to split into more components, and have those components call only the hooks they need, but it is a more complicated fix

**Review by ultrabear — APPROVED** [review]

**Pull request merged**
